name: SyncToGitee

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # 每整点同步一次，对应文档 
    # https://docs.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule
    - cron: '0 * * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # - uses: actions/checkout@v2
          
      # Runs a single command using the runners shell
      - name: Sync Kingfisher
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_KEY }}
        with:
          source-repo: "git@github.com:onevcat/Kingfisher.git"
          destination-repo: "git@gitee.com:jiutianhuanpei/Kingfisher.git"
      
      - name: Sync Alamofire
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_KEY }}
        with:
          source-repo: "git@github.com:Alamofire/Alamofire.git"
          destination-repo: "git@gitee.com:jiutianhuanpei/Alamofire.git"

      - name: Sync ObjectMapper
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_KEY }}
        with:
          source-repo: "git@github.com:tristanhimmelman/ObjectMapper.git"
          destination-repo: "git@gitee.com:jiutianhuanpei/ObjectMapper.git"  
          

      - name: Sync SnapKit
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_KEY }}
        with:
          source-repo: "git@github.com:SnapKit/SnapKit.git"
          destination-repo: "git@gitee.com:jiutianhuanpei/SnapKit.git"  


      - name: Sync AFNetworking
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_KEY }}
        with:
          source-repo: "git@github.com:AFNetworking/AFNetworking.git"
          destination-repo: "git@gitee.com:jiutianhuanpei/AFNetworking.git"   
                   

      - name: Sync SDWebImage
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_KEY }}
        with:
          source-repo: "git@github.com:SDWebImage/SDWebImage.git"
          destination-repo: "git@gitee.com:jiutianhuanpei/SDWebImage.git" 

          
      - name: Sync HBToast
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_KEY }}
        with:
          source-repo: "git@github.com:jiutianhuanpei/HBToast.git"
          destination-repo: "git@gitee.com:jiutianhuanpei/HBToast.git"  
                   
      - name: Sync HBTools
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_KEY }}
        with:
          source-repo: "git@github.com:jiutianhuanpei/HBTools.git"
          destination-repo: "git@gitee.com:jiutianhuanpei/HBTools.git" 

                   
      - name: Sync SQLite.swift
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_KEY }}
        with:
          source-repo: "git@github.com:stephencelis/SQLite.swift.git"
          destination-repo: "git@gitee.com:jiutianhuanpei/SQLite.swift.git"            

      - name: Sync Charts
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_KEY }}
        with:
          source-repo: "git@github.com:danielgindi/Charts.git"
          destination-repo: "git@gitee.com:jiutianhuanpei/Charts.git"            

      - name: Sync Koloda
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_KEY }}
        with:
          source-repo: "git@github.com:Yalantis/Koloda.git"
          destination-repo: "git@gitee.com:jiutianhuanpei/Koloda.git"            

      - name: Sync GPUImage2
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_KEY }}
        with:
          source-repo: "git@github.com:BradLarson/GPUImage2.git"
          destination-repo: "git@gitee.com:jiutianhuanpei/GPUImage2.git"            

      - name: Sync SwiftyJSON
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_KEY }}
        with:
          source-repo: "git@github.com:SwiftyJSON/SwiftyJSON.git"
          destination-repo: "git@gitee.com:jiutianhuanpei/SwiftyJSON.git" 













